scan_timeout = 10
command_timeout = 10000
# format = "$directory$git_branch$git_metrics$character"
# add_newline = false
# line_break.disabled = true
# directory.style = "purple"

# [character]
# success_symbol = "[](purple)"
# error_symbol = "[](blue)"

# [git_branch]
# style = "pink"
# symbol = ""

# [git_metrics]
# disabled = true
# added_style = "bold green"
# deleted_style = "bold red"
## ░█▀▀░▀█▀░█▀█░█▀▄░█▀▀░█░█░▀█▀░█▀█
## ░▀▀█░░█░░█▀█░█▀▄░▀▀█░█▀█░░█░░█▀▀
## ░▀▀▀░░▀░░▀░▀░▀░▀░▀▀▀░▀░▀░▀▀▀░▀░░
# Setups
format="$directory$git_branch$character"
right_format = """$git_status$cmd_duration"""
add_newline = false 

# Other languages configurations:
c.disabled = true
cmake.disabled = true
haskell.disabled = true
python.disabled = true
ruby.disabled = true
rust.disabled = true
perl.disabled = true
package.disabled = true
lua.disabled = true
nodejs.disabled = true
java.disabled = true
golang.disabled = true

[conda]
format = ' [$symbol$environment](dimmed green) '

# Prompt symbols 
[character]
success_symbol = "[](#8EC07C bold)"
error_symbol = "[](#AD685A)"
vicmd_symbol = "[](#DD8F6E)"

[directory]
format = "[]($style)[ ](bg:#7C5CDD fg:#DD8F6E)[$path](bg:#7C5CDD fg:#83A598 bold)[ ]($style)"
style = "bg:none fg:#7C5CDD"
truncation_length = 3
truncate_to_repo=false

[git_branch]
format = "[]($style)[[ ](bg:#312C2E fg:#8EC07C bold)$branch](bg:#312C2E fg:#83A598)[ ]($style)"
style = "bg:none fg:#7C5CDD"

[git_status]
# $all status$ahead_behind
format = "[]($style)[$all_status$ahead_behind](bg:#312C2E fg:#b4befe)[ ]($style)"
style = "bg:none fg:#7C5CDD"
conflicted = "="
ahead =	"⇡${count}"
behind = "⇣${count}"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"
up_to_date = ""
untracked = "?${count}"
stashed = ""
modified = "!${count}"
staged = "+${count}"
renamed = "»${count}"
deleted = "${count}"

[cmd_duration]
min_time = 1
# duration & style 
format = "[]($style)[[神](bg:#7C5CDD fg:#eba0ac bold)$duration](bg:#7C5CDD fg:#E0DFE0)[ ]($style)"
disabled = false
# style = "bg:none fg:#312C2E"
style = "bg:none fg:#7C5CDD"

# bg=#7C5CDD
# fg=#E0DFE0

# gum pink
# #D373B3 # #FF87D7

# Gum blue
# #5353D3 #5F5FFF (no transparency)
# gum blue FG (yellow-ish)
# #D3D373 # #FDFD8A

# Left is with transparency - Right is none (or single)
# #303030 - black BG
# #DDDB96 #ECF380 - Text FG
# #DE78E5 #EE6FF8 - Pink
# #DC7C7D #FF8787 - Peach/Orange
# #D7875F - Orange
# #1FABEC #00AFFF - Blue
# #62E1A1 #00AF5F - Green
# #008787 - Forest Green
# #FF5F5F - Red
# #C6C6C6 - White

# #2B4E3C
#E178BE
#EE6FF8