#!/bin/bash

env = LIBVA_DRIVER_NAME,nvidia
env = XDG_SESSION_TYPE,wayland
env = GBM_BACKEND,nvidia-drm
env = __GLX_VENDOR_LIBRARY_NAME,nvidia
env = WLR_NO_HARDWARE_CURSORS,1
WLR_NO_HARDWARE_CURSORS=1
# if firefox crashes remove GBM_BACKEND,nvidia-drm
# If you face problems with Discord windows not displaying or screen sharing not working in Zoom
# remove or comment the line: 
#env = __GLX_VENDOR_LIBRARY_NAME,nvidia.
exec Hyprland