#!/bin/sh

[ -n "$1" ] && wallpaper_path="$1"

[ -z "$wallpaper_path" ] && wallpaper_path="$HOME/Pictures/$(ls ~/Pictures |
	while read A; do echo -en "$A\x00icon\x1f~/Pictures/$A\n"; done | rofi -dmenu -p "" -theme ~/.config/rofi/styles/image-preview.rasi)"
[ -z "$wallpaper_path" ] && exit 1

