#!/bin/sh

#check if user wants to clean up a terminated download with ^C
trap ctrl_c INT
ctrl_c () {
    read -p " Download terminated. Clean up unfinished download? (Y/n): " yn
	case $yn in
    	[Yy]*) if [ "$TITLE" = "" ]; then exit; else rm -rf "$BOOKDIR/$TITLE" && echo "Manga successfully deleted!" && exit; fi ;;
    	[Nn]*) rm "$BOOKDIR/$TITLE/tempindex" && echo "Happy fapping!" && exit ;;
    	*) rm -rf "$BOOKDIR/$TITLE" && echo "Manga successfully deleted!" && exit ;;
    esac
}

cbz_compress () {
	TITLE="$(grep -Po '(?<=</span><span class="pretty">).*(?=</span></h1><h2 class="title"><span class="before">)' tempindex | sed 's/span><span class="after">//g' | sed 's/<//' | sed "s|/||g" | sed "s/&#x27;/'/g" | sed "s/|/--/g")"
	rm tempindex
	cd "$BOOKDIR"
	zip -r "$TITLE".cbz "$TITLE/" > /dev/null
	rm -rf "$TITLE"
	echo "Happy fapping!"
	return
}

download () {
	if [ "$2" = "random" ]; then
		CODE="$(shuf -i 1-400000 -n 1)"
	else
		CODE="$2"
	fi
	if [ -d "$HOME/.cache/nhdl" ]; then
		true
	else
		mkdir -p "$HOME/.cache/nhdl"
	fi
	echo $CODE >> $HOME/.cache/nhdl/history
	BOOKDIR="$(cat $HOME/.config/nhdl/books.dir)"
	if [ -d "$BOOKDIR" ]; then
		printf "Book will be stored in $BOOKDIR/\n\n"
	else
		echo "Books directory does not exist! Default automatically set to ~/Documents/Books/"
		echo "This can be changed by editing ~/.config/nhdl/books.dir"
		mkdir -p "$HOME/.config/nhdl"
		echo "$HOME/Documents/Books" > "$HOME/.config/nhdl/books.dir"
		BOOKDIR="$HOME/Documents/Books"
		mkdir -p "$BOOKDIR"
	fi

	#check if manga exists
	if [ "$(echo "$CODE" | sed 's/[0-9]*//')" = "" ]; then
		true
	else
		echo "Invalid code!"
		return
	fi
	cd "$BOOKDIR"
	TITLE="$(curl -s "https://nhentai.net/g/$CODE/" | grep -Po '(?<=</span><span class="pretty">).*(?=</span></h1><h2 class="title"><span class="before">)' | sed 's/span><span class="after">//g' | sed 's/<//' | sed "s|/||g" | sed "s/&#x27;/'/g" | sed "s/|/--/g")"
	if [ "$TITLE" = "" ]; then
		echo "Invalid code!"
		return
	fi
	echo Downloading \"$TITLE\" "($CODE)"

	#check if manga was already DLed
	if [ -d "$TITLE" ]; then
		FILENUM=$(ls -1 "$TITLE" | wc -l)
		read -p "Directory already exists, with a total of $FILENUM pages downloaded. Erase and continue? (y/N): " yn
    	case $yn in
        	[Yy]*) rm -rf "$TITLE" ;;
        	[Nn]*) return ;;
        	*) return ;;
		esac
	fi
	mkdir "$TITLE"
	cd "$TITLE"
	if [ -f "$TITLE".cbz ]; then
		read -p "CBZ file already exists. Erase and continue? (y/N): " yn
    	case $yn in
        	[Yy]*) rm "$TITLE".cbz && echo "Manga erased! Redownloading..." ;;
        	[Nn]*) return ;;
        	*) return ;;
		esac
	fi
	curl -s "https://nhentai.net/g/$CODE/" -o tempindex

	PAGENUM=1
	PAGECOUNT=$(grep -Po '(?<="name"\>)[0-9]*(?=\<\/span)' tempindex)
	GYARU="$(sed "s/.*galleries//;s/cover.*//" tempindex | sed "s|/||g" | head -n 5 | tail -n 1)"
	echo ""
	for i in $(seq $PAGECOUNT); do
		printf "%s\n" "Downloading page $PAGENUM of $PAGECOUNT"
		wget -q "https://i.nhentai.net/galleries/$GYARU/$PAGENUM.jpg" || wget -q "https://i.nhentai.net/galleries/$GYARU/$PAGENUM.png"
		PAGENUM="$(expr $PAGENUM + 1)"
	done
	echo ""
	SOFAR=$(cat "$HOME/.cache/nhdl/history" | wc -l)
	echo "Doujins downloaded thus far: $SOFAR"
	if [ $SOFAR = 100 ]; then
		echo "Wow! 100! What a coomer!"
	fi
    read -p "Would you like to compress your manga to .cbz format? (Y/n): " yn
    case $yn in
    	[Yy]*) cbz_compress ;;
    	[Nn]*) rm "$BOOKDIR/$TITLE/tempindex" && echo "Happy fapping!" && return ;;
    	*) cbz_compress ;;
    esac
}

collector () {
	COLLECTNUM=1
	RESULTS="$(curl -s "https://nhentai.net/search/?q=." | grep -o -P "[0-9]{3},[0-9]{3} results" | sed "s/,//" | sed "s/ results//")"
	TOTAL="$(expr $RESULTS + 6159)"
	for i in $(seq $TOTAL); do
		yes | download $COLLECTNUM
		COLLECTNUM="$(expr $COLLECTNUM + 1)"
	done
	echo "Wow! You're done collecting every manga!"
	return
}

nhdl_search () {
	echo "Searching for \"$2\""
	QUERY="$(echo $2 | sed 's/ /+/g')"
	read -p "Sort by recent or most popular (r/p)?: " rp
	case $rp in
		[Pp]*) SORT="popular" ;;
		[Rr]*) SORT="recent" ;;
	esac
	curl -s "https://nhentai.net/search/?q="$QUERY"&sort="$SORT"" | sed "s/.*content//;s/image.*//" | fzf
}

nhdl_help () {
	printf "nHentai Manga Downloader (nhdl) by swindlesmccoop\n\nUsage: nhdl [-dh] [code]\n-d, --download: (D)ownload [code] of the manga's gallery\n-h, --help: Print this (h)elp message\n" && return 1
}

#if no parameters are supplied, print help
if [ $# -eq 0 ]; then nhdl_help; fi

case "$1" in
	--collect-all) collector ;;
	-d) download "$@" ;;
	-h) nhdl_help ;;
	--help) nhdl_help ;;
	-s) nhdl_search "$@" ;;
esac
