#!/bin/sh
set -e

cd ~/.local/share/applications
grep -rn 'Exec=steam' | grep -oP '.*(?=\.desktop:)' |
    grep -v -e Proton -e 'Steam Linux' |
    sort -Vu | wofi --dmenu -i -c -l 10 | while read -r file
do
    file=${file}.desktop
    if [ -f "$file" ];then
        notify-send "Executing..." "$file"
        exec=$(grep -oP '(?<=Exec=).*' "$file")
		hyprland dispatch exec [ workspace 3 ] exec "$exec"
    fi
    break
done
